springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: noneh
    filter: true
    theme: dark
  api-docs:
    path: /openapi
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/japaneseLms
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
