springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: noneh
    filter: true
    theme: dark
  api-docs:
    path: /openapi
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
